source("readfile.R")
#power <- read.table("../household_power_consumption.txt",header=TRUE,sep=";",na.string="?",colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
#plotdata <- subset(power,Date == "1/2/2007" | Date == "2/2/2007")
#plotdata$Date <- strptime(paste(plotdata$Date,plotdata$Time),"%d/%m/%Y %H:%M:%S")
png(filename="plot2.png",width=480,height=480)
plot(plotdata$Date, plotdata$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.off()